trace:
  endpoint: http://127.0.0.1:14268/api/traces
server:
  http:
    addr: 0.0.0.0:8011
    timeout: 1s
  grpc:
    addr: 0.0.0.0:12000
    timeout: 1s
data:
  database:
    driver: mysql
    source: root:root@tcp(127.0.0.1:3306)/test?parseTime=True&loc=Local
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
auth:
  api_key: asdk2llqxxk''''a
  service_key: 238883732_23_jjsad_e_88+13scc,,kd231kkk
  ttl: 86400