// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"go.opentelemetry.io/otel/sdk/trace"
	"kratos_sim/app/session/service/internal/biz"
	"kratos_sim/app/session/service/internal/conf"
	"kratos_sim/app/session/service/internal/data"
	"kratos_sim/app/session/service/internal/server"
	"kratos_sim/app/session/service/internal/service"

	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, registry *conf.Registry, logger log.Logger, tp *trace.TracerProvider) (*kratos.App, func(), error) {
	gormDB := data.NewDB(confData, logger)
	dataData, cleanup, err := data.NewData(gormDB, logger)
	if err != nil {
		return nil, nil, err
	}
	sessionRepo := data.NewSessionRepo(dataData, logger)
	sessionUsecase := biz.NewSessionUseCase(sessionRepo, logger)
	relationRepo := data.NewRelationRepo(dataData, logger)
	relationUseCase := biz.NewRelationUseCase(relationRepo, logger)
	sessionService := service.NewSessionService(sessionUsecase, relationUseCase, logger)
	grpcServer := server.NewGRPCServer(confServer, sessionService, logger, tp)
	registrar := server.NewRegistrar(registry)
	app := newApp(logger, grpcServer, registrar)
	return app, func() {
		cleanup()
	}, nil
}
