trace:
  endpoint: http://127.0.0.1:14268/api/traces
server:
  grpc:
    addr: 0.0.0.0:13000
    timeout: 1s
  websocket:
    path: /ws
    addr: 0.0.0.0:13010
    timeout: 1s
data:
  database:
    driver: mysql
    source: root:123456@tcp(127.0.0.1:3306)/my_prod?parseTime=True&loc=Local
    prefix: sim_
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
